version: "3"
services:
    rabbit1:
        image: "rabbitmq:management-alpine"
        hostname: "rabbit1"
        container_name: "rabbit1"
        environment:
            RABBITMQ_ERLANG_COOKIE: "COOKIEMONSTER"
            RABBITMQ_DEFAULT_USER: "admin"
            RABBITMQ_DEFAULT_PASS: "admin"
            RABBITMQ_DEFAULT_VHOST: "/"
            RABBITMQ_NODENAME: "rabbit"
            # RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit cluster_partition_handling [pause_minority]"            
        ports:
            - "15672:15672"
            - "5672:5672"
        volumes:
          -  "./app:/app"
    rabbit2:
        image: "rabbitmq:management-alpine"
        hostname: "rabbit2"
        container_name: "rabbit2"
        environment:
            RABBITMQ_ERLANG_COOKIE: "COOKIEMONSTER"
            RABBITMQ_DEFAULT_USER: "admin"
            RABBITMQ_DEFAULT_PASS: "admin"
            RABBITMQ_DEFAULT_VHOST: "/"
            RABBITMQ_NODENAME: "rabbit"
            RABBITMQ_PARENT_NODENAME: "rabbit@rabbit1"
            # RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit cluster_partition_handling [pause_minority]"
    
    rabbit3:
        image: "rabbitmq:management-alpine"
        hostname: "rabbit3"
        container_name: "rabbit3"
        environment:
            RABBITMQ_ERLANG_COOKIE: "COOKIEMONSTER"
            RABBITMQ_DEFAULT_USER: "admin"
            RABBITMQ_DEFAULT_PASS: "admin"
            RABBITMQ_DEFAULT_VHOST: "/"
            RABBITMQ_NODENAME: "rabbit"
            RABBITMQ_PARENT_NODENAME: "rabbit@rabbit1"
            # RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit cluster_partition_handling [pause_minority]"